name: Deploy to Google Cloud

on:
  push:
    branches: [main] # Or whatever branch triggers the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.LAVANYA_KOPPISETTI }}

      # Add your deployment steps here.  For example:
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-service --image gcr.io/your-project/your-image --region us-central1
